### PR TITLE
Added new trainings for 80X next to old ones

### PR DESCRIPTION
**Pull request by smoortga**
Added new trainings next to old ones with new names for easier merging with cmssw PR.

This PR should replace the one that is currently pending: https://github.com/cms-data/RecoBTag-CTagging/pull/2
And also the revert of the merge that happened for that PR:
https://github.com/cms-data/RecoBTag-CTagging/pull/3

Now that the new trainings are next to the old ones, this PR can safely be merged without conflicting with any cmssw tests. Once this merge is complete, the CMSSW PR (https://github.com/cms-sw/cmssw/pull/13054) can be merged with the new naming convention in place.

@slava77 @mverzett

### CODE REVIEW

**Comment by mverzett** [comment]
As agreed with @slava77 we will take care of removing the now outdated files once everything is merged and working.

**Comment by slava77** [comment]
Looking at https://github.com/smoortga/RecoBTag-CTagging/compare/a2d6ff7...90a017c6 which is what I expect is a comparison with the old version (before #2 went in and got overwritten),
I see only an addition of new files.
This is good.

https://github.com/cms-data/RecoBTag-CTagging/pull/4/files shows changes to old files as well. Is this due to some feature of the revert that didn't revert everything?
@degano do you know?

Based on https://github.com/smoortga/RecoBTag-CTagging/compare/a2d6ff7...90a017c6, I think this PR can be merged.
... if the https://github.com/cms-data/RecoBTag-CTagging/pull/4/files is right and the revert of  #2 in #3  actually didn't go back to the original files, then I think this PR needs to be merged ASAP.

**Comment by smoortga** [comment]
I think what happened in https://github.com/cms-data/RecoBTag-CTagging/pull/4/files  is the following:

I went back to my latest local commit in which I replaced the old files by the new ones keeping the names as they were. Since this was not good, I copied these new trainings to the new .xml names (with the extention "_sklearn"), and I copied the old training files own-handed again in the repository. That explains wht github thinks I changed the files without the extension, and added the ones with the extension.
So I think this PR can indeed safely be merged. I checked in an editor and all training files seem to be the correct ones.

**Comment by slava77** [comment]
@degano @smuzaffar 
please propagate these updates to the IB

**Comment by ghost** [comment]
@slava77 The CMSDIST PR is in testing here: cms-sw/cmsdist#2087

**Pull request merged**
