### PR TITLE
Added new c-tagger retrainings for Phase I

### PR DESCRIPTION
**Pull request by smoortga**
This PR adds the new c-tagger retraining xml files for Phase I. These training will be included in a PR that will be made for 91X once this is merged.

one question: currently the old trainings are still in this repository. c_vs_b(udsg).weight.xml are the oldest and are not used anymore. c_vs_b(udsg)_sklearn.weight.xml are the ones currently in operation. Is it ok to just keep them in for backward compatibility? Or should I remove the oldest ones?

Cheers
Seth

### CODE REVIEW

**Comment by smoortga** [comment]
Dear @smuzaffar @iahmad-khan and @davidlange6 ,

Since we would like to add this new c-tagger retraining in the last open pre-release for 91X (9_1_0_pre3, deadline next week tuesday the 11th of April), I would like to ask if this can be merged on a short timescale such that I can also make a PR to actually use this training by default before the deadline.

Thanks in advance!
Best regards,
Seth Moortgat

**Comment by smuzaffar** [comment]
we are working on it.

**Comment by smoortga** [comment]
Thanks a lot! (I don't want to sound impatient, just checking if it is being picked up.)

Cheers

**Comment by smoortga** [comment]
@smuzaffar, Is it safe now for me to make a PR to cmssw that reads in this training file by default? or should I wait a day or so to make sure these xml files are available when the unit tests are ran?

Perhaps I should wait untill these tests finish first: https://github.com/cms-sw/cmsdist/pull/2939 ?

**Comment by smuzaffar** [comment]
yes, it is better to make a cmssw PR now so that both cmssw and cmsdist PR can be tested together.

**Comment by smoortga** [comment]
Ok I will also make the cmssw PR and reference it here, thanks.

**Pull request merged**
